name: dev
on: [pull_request, push]
env:
  CI: true

jobs:
  prettier:
    name: Format code
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup node & npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Format
        run: npm run format

      # Setup a "bot" name & email for our commit step
      # using the GitHub Actions bot user: https://github.community/t/github-actions-bot-email-address/17204/6
      - name: Configure git
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Only commit if there's a change. Ref https://stackoverflow.com/a/8123841
      - name: Commit formatted code
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m 'chore: Format code'
          git push

  test:
    name: Tests for Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup node & npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test
